In [2]:
#### 시리즈 - 1차원

#### 데이터프레임?
# - 2차원 표 형태의 자료구조로, 행과 열로 구성되어 있습니다. 
# - 각 열은 서로 다른 데이터 유형을 가질 수 있으며, 각 행은 관측값을 나타냅니다. 
# - 데이터프레임은 판다스 라이브러리에서 제공하는 주요 자료구조 중 하나로, 
# - 데이터를 효율적으로 저장하고 조작할 수 있도록 설계되었습니다.
# - 데이터프레임은 다양한 데이터 분석 작업에 사용되며, 
# - 데이터 정제, 변환, 시각화 등 다양한 기능을 제공합니다. 
# - 데이터프레임을 사용하면 데이터를 쉽게 필터링, 그룹화, 집계할 수 있으며, 
# - 다양한 통계적 분석과 머신러닝 모델링에도 활용됩니다. 
# - 데이터프레임은 특히 대규모 데이터셋을 다룰 때 유용하며, 
# - 데이터 과학자와 분석가들에게 널리 사용되는 도구입니다.

In [3]:
# pip install -U jupyter ipykernel notebook
# pip install pandas
# 실행이 안되면 커널을 다시시작

In [4]:
import pandas as pd

# 딕셔너리 자료를 data 객체에 저장
data = {'name': ['Mark', 'Jane', 'Chris', 'Ryan'],
        'age': [33, 32, 44, 42],
        'score': [91.3, 83.4, 77.5, 87.7]}

print(data)

{'name': ['Mark', 'Jane', 'Chris', 'Ryan'], 'age': [33, 32, 44, 42], 'score': [91.3, 83.4, 77.5, 87.7]}

In [5]:
# DataFrame() 함수로 data 객체를 데이터프레임으로 만들어 df 객체에 저장
df = pd.DataFrame(data)
df

    name  age  score
0   Mark   33   91.3
1   Jane   32   83.4
2  Chris   44   77.5
3   Ryan   42   87.7

In [6]:
# 합계
print(df.sum())

name     MarkJaneChrisRyan
age                    151
score                339.9
dtype: object

In [7]:
# df → DataFrame 객체
# .mean() → 평균 계산
# numeric_only=True → 숫자 데이터만 사용
# print(df.mean()) -> 에러
print(df.mean(numeric_only=True))

age      37.750
score    84.975
dtype: float64

In [8]:
# 데이터 선택하기
print(df.age)
print(df['age'])

0    33
1    32
2    44
3    42
Name: age, dtype: int64
0    33
1    32
2    44
3    42
Name: age, dtype: int64

In [9]:
import re, os
os.chdir(r'E:\wi\git\py0811\p05')

In [10]:
# 판다스로 CSV 파일 읽기
# read_csv() → CSV 파일 읽기
# thousands=','
# → 1,000, 25,300 같은 값을 숫자로 변환
df = pd.read_csv('apt2308.csv', thousands=',')
# df = pd.read_csv('apt2308.csv', encoding='utf8', thousands=',')
# df = pd.read_csv('apt2308.csv', encoding='utf-8', thousands=',')
df

,시군구,번지,본번,부번,단지명,전용면적,계약년월,계약일,거래금액,층,건축년도,도로명,해제사유발생일,등기신청일자,거래유형,중개사소재지
0,강원특별자치도 강릉시 견소동,202,202,0,송정한신,59.800,202308,8,23000,9,1997.0,경강로2539번길 8,NaN,,중개거래,강릉시
1,강원특별자치도 강릉시 견소동,202,202,0,송정한신,84.945,202308,14,31000,13,1997.0,경강로2539번길 8,NaN,,중개거래,강릉시
2,강원특별자치도 강릉시 견소동,202,202,0,송정한신,43.380,202308,30,16400,10,1997.0,경강로2539번길 8,NaN,,중개거래,강릉시
3,강원특별자치도 강릉시 견소동,289,289,0,송정해변신도브래뉴아파트,59.990,202308,19,24500,5,2005.0,경강로2539번길 23,NaN,,중개거래,강릉시
4,강원특별자치도 강릉시 견소동,289,289,0,송정해변신도브래뉴아파트,84.990,202308,22,28500,4,2005.0,경강로2539번길 22,NaN,,중개거래,강릉시
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26504,충청북도 충주시 호암동,1063,1063,0,충주호암두진하트리움아파트,66.957,202308,16,34100,15,2019.0,호암수청2로 78,NaN,,중개거래,충북 충주시
26505,충청북도 충주시 호암동,1063,1063,0,충주호암두진하트리움아파트,84.803,202308,19,41000,12,2019.0,호암수청2로 78,NaN,,중개거래,충북 충주시
26506,충청북도 충주시 호암동,547-6,547,6,호반현대,84.960,202308,12,15700,2,1994.0,신촌2길 29,NaN,,중개거래,충북 충주시
26507,충청북도 충주시 호암동,221-1,221,1,호암리버빌(2단지),84.680,202308,10,20700,3,2002.0,호암중앙2로 5,NaN,,중개거래,충북 충주시
26508,충청북도 충주시 호암동,1191,1191,0,호암힐데스하임,84.950,202308,21,40200,11,2019.0,호암토성2로 1,NaN,,중개거래,충북 충주시

In [11]:
# 26509개의 자료가 들어있다.
print(len(df))

26509

In [12]:
# 데이터프레임 살펴보기
# 처음 5개 행만 출력
print(df.head())

               시군구   번지   본번  부번           단지명    전용면적    계약년월  계약일   거래금액  \
0  강원특별자치도 강릉시 견소동  202  202   0          송정한신  59.800  202308    8  23000
1  강원특별자치도 강릉시 견소동  202  202   0          송정한신  84.945  202308   14  31000
2  강원특별자치도 강릉시 견소동  202  202   0          송정한신  43.380  202308   30  16400
3  강원특별자치도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트  59.990  202308   19  24500
4  강원특별자치도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트  84.990  202308   22  28500

    층    건축년도           도로명  해제사유발생일 등기신청일자  거래유형 중개사소재지
0   9  1997.0   경강로2539번길 8      NaN         중개거래    강릉시
1  13  1997.0   경강로2539번길 8      NaN         중개거래    강릉시
2  10  1997.0   경강로2539번길 8      NaN         중개거래    강릉시
3   5  2005.0  경강로2539번길 23      NaN         중개거래    강릉시
4   4  2005.0  경강로2539번길 22      NaN         중개거래    강릉시

In [13]:
# 마지막 5개 행만 출력
print(df.tail())

                시군구     번지    본번  부번            단지명    전용면적    계약년월  계약일  \
26504  충청북도 충주시 호암동   1063  1063   0  충주호암두진하트리움아파트  66.957  202308   16
26505  충청북도 충주시 호암동   1063  1063   0  충주호암두진하트리움아파트  84.803  202308   19
26506  충청북도 충주시 호암동  547-6   547   6           호반현대  84.960  202308   12
26507  충청북도 충주시 호암동  221-1   221   1     호암리버빌(2단지)  84.680  202308   10
26508  충청북도 충주시 호암동   1191  1191   0        호암힐데스하임  84.950  202308   21

        거래금액   층    건축년도        도로명  해제사유발생일 등기신청일자  거래유형  중개사소재지
26504  34100  15  2019.0  호암수청2로 78      NaN         중개거래  충북 충주시
26505  41000  12  2019.0  호암수청2로 78      NaN         중개거래  충북 충주시
26506  15700   2  1994.0    신촌2길 29      NaN         중개거래  충북 충주시
26507  20700   3  2002.0   호암중앙2로 5      NaN         중개거래  충북 충주시
26508  40200  11  2019.0   호암토성2로 1      NaN         중개거래  충북 충주시

In [14]:
# 열 전체 자료 출력하기
print(df['시군구'])

0        강원특별자치도 강릉시 견소동
1        강원특별자치도 강릉시 견소동
2        강원특별자치도 강릉시 견소동
3        강원특별자치도 강릉시 견소동
4        강원특별자치도 강릉시 견소동
              ...
26504       충청북도 충주시 호암동
26505       충청북도 충주시 호암동
26506       충청북도 충주시 호암동
26507       충청북도 충주시 호암동
26508       충청북도 충주시 호암동
Name: 시군구, Length: 26509, dtype: str

In [15]:
# 조건별로 출력하기
# 전용면적이 80을 넘으면 True, 아니면 False
print(df['전용면적'] > 80)

0        False
1         True
2        False
3        False
4         True
         ...
26504    False
26505     True
26506     True
26507     True
26508     True
Name: 전용면적, Length: 26509, dtype: bool

In [16]:
# 전용면적이 80을 넘는 데이터프레임만 출력
print(df[df['전용면적'] > 240])

                 시군구      번지   본번  부번       단지명      전용면적    계약년월  계약일  \
14988   부산광역시 남구 용호동     944  944   0  오륙도에스케이뷰  244.8647  202308    4
16292  서울특별시 강남구 도곡동     467  467   0    타워팰리스1  244.6600  202308    5
16297  서울특별시 강남구 도곡동  467-29  467  29    타워팰리스3  244.2240  202308   18
16326  서울특별시 강남구 신사동   649-5  649   5   알파임하우스1  242.1600  202308    2
17619  서울특별시 서초구 반포동   20-43   20  43      반포자이  244.9720  202308    2
17638  서울특별시 서초구 방배동   757-3  757   3       삼호3  257.1200  202308    5

         거래금액   층    건축년도         도로명  해제사유발생일    등기신청일자  거래유형          중개사소재지
14988  200000  21  2008.0     오륙도로 85      NaN            중개거래           부산 남구
16292  745000  50  2002.0   언주로30길 56      NaN            중개거래          서울 강남구
16297  670000  62  2004.0   언주로30길 26      NaN  20230823  중개거래  서울 강남구, 서울 서초구
16326  550000   9  2002.0  언주로164길 20      NaN            중개거래          서울 강남구
17619  650000  23  2009.0    신반포로 270      NaN            중개거래          서울 서초구
17638  262000  10  1976.0   방배로43길 30      NaN            중개거래          서울 서초구

In [17]:
# 전용면적이 80m²을 넘는 아파트 단지명 출력
print(df['단지명'][df['전용면적'] > 240])

14988    오륙도에스케이뷰
16292      타워팰리스1
16297      타워팰리스3
16326     알파임하우스1
17619        반포자이
17638         삼호3
Name: 단지명, dtype: str

In [18]:
# 전용면적이 130m²가 넘고 거래금액이 3억 원 미만인 아파트 단지명 출력
# 논리 연산자: 
# -> &(그리고 - 모든 조건이 참이면 참)
# -> |(또는 - 하나 이상 참이면 참)
print(df['단지명'][(df['전용면적'] > 130) & (df['거래금액'] < 30000)])

140       현대5차
256       레이크뷰
370      라이프타운
392       현대3차
407         두산
         ...
25655       건영
25657       건영
25840       신라
25891     세원홍실
26016       동아
Name: 단지명, Length: 74, dtype: str

In [19]:
# 전용면적이 130m²가 넘거나 거래금액이 3억 원 미만인 아파트 단지명 출력
print(df['단지명'][(df['전용면적'] > 130) | (df['거래금액'] < 30000)])

0                 송정한신
2                 송정한신
3         송정해변신도브래뉴아파트
4         송정해변신도브래뉴아파트
6          강릉교동롯데캐슬1단지
             ...
26499               진도
26500               진도
26503    충주호암두진하트리움아파트
26506             호반현대
26507       호암리버빌(2단지)
Name: 단지명, Length: 14054, dtype: str

In [20]:
# 원하는 자료만 살펴보기
# df.loc[행선택, 열선택]
# loc는 label-based location indexer

# '단지명'과 '거래금액'만 10개 행출력
# :10 -> 0~10행까지 선택
# ['단지명', '거래금액'] -> 두 컬럼만 선택
print(df.loc[:10, ['단지명', '거래금액']])

             단지명   거래금액
0           송정한신  23000
1           송정한신  31000
2           송정한신  16400
3   송정해변신도브래뉴아파트  24500
4   송정해변신도브래뉴아파트  28500
5   송정해변신도브래뉴아파트  32500
6    강릉교동롯데캐슬1단지  60000
7    강릉교동롯데캐슬2단지  37500
8   강릉교동풍림아이원아파트  35400
9   강릉교동풍림아이원아파트  31000
10         교동3주공  27500

In [21]:
# 10억 원을 초과하는 가격으로 거래된 아파트
print(df.loc[:, ['단지명', '거래금액']][df['거래금액'] > 100000])

                      단지명    거래금액
1191            DMC디에트르한강  129000
1192           DMC한강에일린의뜰  130000
1193           DMC한강에일린의뜰  115000
1446             일산요진와이시티  155000
1449             일산요진와이시티  102000
...                   ...     ...
20912         송도센트럴파크푸르지오  101000
20913        송도아메리칸타운아이파크  121000
20933          송도자이하버뷰2단지  160000
24887  천안 불당 지웰시티푸르지오 2단지  105000
24895            천안불당지웰더샵  110000

[1229 rows x 2 columns]

In [22]:
# 새로운 값 추가하기
# df['새로운열이름'] = 값

# 전용면적 대비 거래금액을 '단가'라는 이름으로 저장
df['단가'] = df['거래금액'] / df['전용면적']

df.loc[:10, ('거래금액', '전용면적', '단가')]

     거래금액      전용면적          단가
0   23000   59.8000  384.615385
1   31000   84.9450  364.942021
2   16400   43.3800  378.054403
3   24500   59.9900  408.401400
4   28500   84.9900  335.333569
5   32500   84.9900  382.397929
6   60000  163.9852  365.886678
7   37500   84.9855  441.251743
8   35400   66.0388  536.048505
9   31000   66.0388  469.421007
10  27500   59.8400  459.558824

In [23]:
# 데이터 정렬(sort)
# df.sort_values(by='열이름') -> 오름차순
print(df.sort_values(by='거래금액').loc[:, ('거래금액', '시군구')])

         거래금액               시군구
22606     630  전라북도 익산시 낭산면 용기리
22610     630  전라북도 익산시 낭산면 용기리
22611     630  전라북도 익산시 낭산면 용기리
22612     630  전라북도 익산시 낭산면 용기리
22614     630  전라북도 익산시 낭산면 용기리
...       ...               ...
17619  650000     서울특별시 서초구 반포동
16297  670000     서울특별시 강남구 도곡동
17622  700000     서울특별시 서초구 반포동
16292  745000     서울특별시 강남구 도곡동
17714  900000   서울특별시 성동구 성수동1가

[26509 rows x 2 columns]

In [24]:
# df.sort_values(by='열이름', ascending=False) -> 내림차순
print(df.sort_values(by='거래금액', ascending=False).loc[:, ('거래금액', '시군구')])

         거래금액               시군구
17714  900000   서울특별시 성동구 성수동1가
16292  745000     서울특별시 강남구 도곡동
17622  700000     서울특별시 서초구 반포동
16297  670000     서울특별시 강남구 도곡동
17619  650000     서울특별시 서초구 반포동
...       ...               ...
22609     630  전라북도 익산시 낭산면 용기리
22614     630  전라북도 익산시 낭산면 용기리
22613     630  전라북도 익산시 낭산면 용기리
22612     630  전라북도 익산시 낭산면 용기리
22615     630  전라북도 익산시 낭산면 용기리

[26509 rows x 2 columns]

In [25]:
# 4억이 넘는 집만 먼저 추출
# 전용면적 기준으로 오름차순 정렬
# 정렬한 데이터프레임에서 ('거래금액', '전용면적', '시군구') 정보만 추출

print(df[df['거래금액'] > 40000].sort_values(by='전용면적').loc[:, ('거래금액', '전용면적', '시군구')])

         거래금액      전용면적              시군구
17949   51000   25.6500    서울특별시 송파구 문정동
17992   93000   27.6800    서울특별시 송파구 잠실동
17646   50500   28.8500    서울특별시 서초구 서초동
18280   47600   30.1355  서울특별시 영등포구 영등포동
18281   44000   30.2372  서울특별시 영등포구 영등포동
...       ...       ...              ...
16297  670000  244.2240    서울특별시 강남구 도곡동
16292  745000  244.6600    서울특별시 강남구 도곡동
14988  200000  244.8647     부산광역시 남구 용호동
17619  650000  244.9720    서울특별시 서초구 반포동
17638  262000  257.1200    서울특별시 서초구 방배동

[8711 rows x 3 columns]

In [26]:
# 문자열 다루기
# df['검색할열'].str.contains('찾는문자열')

# '시군구'에서 '강릉'을 포함한 거래는 True 반환, 없다면 False
print(df['시군구'].str.contains('강릉'))

0         True
1         True
2         True
3         True
4         True
         ...
26504    False
26505    False
26506    False
26507    False
26508    False
Name: 시군구, Length: 26509, dtype: bool

In [27]:
print(df[df['시군구'].str.contains('강릉')])

                 시군구    번지    본번  부번           단지명     전용면적    계약년월  계약일  \
0    강원특별자치도 강릉시 견소동   202   202   0          송정한신  59.8000  202308    8
1    강원특별자치도 강릉시 견소동   202   202   0          송정한신  84.9450  202308   14
2    강원특별자치도 강릉시 견소동   202   202   0          송정한신  43.3800  202308   30
3    강원특별자치도 강릉시 견소동   289   289   0  송정해변신도브래뉴아파트  59.9900  202308   19
4    강원특별자치도 강릉시 견소동   289   289   0  송정해변신도브래뉴아파트  84.9900  202308   22
..               ...   ...   ...  ..           ...      ...     ...  ...
127  강원특별자치도 강릉시 홍제동  1044  1044   0   엘에이치미디어촌6단지  59.9800  202308   23
128  강원특별자치도 강릉시 홍제동  1037  1037   0        우미린아파트  84.9843  202308   24
129  강원특별자치도 강릉시 홍제동  1037  1037   0        우미린아파트  84.9819  202308   25
130  강원특별자치도 강릉시 회산동   610   610   0      강릉회산한신더휴  84.9610  202308    7
131  강원특별자치도 강릉시 회산동   130   130   0       힐스테이트강릉  84.9925  202308   21

      거래금액   층    건축년도           도로명  해제사유발생일 등기신청일자  거래유형       중개사소재지  \
0    23000   9  1997.0   경강로2539번길 8      NaN         중개거래          강릉시
1    31000  13  1997.0   경강로2539번길 8      NaN         중개거래          강릉시
2    16400  10  1997.0   경강로2539번길 8      NaN         중개거래          강릉시
3    24500   5  2005.0  경강로2539번길 23      NaN         중개거래          강릉시
4    28500   4  2005.0  경강로2539번길 22      NaN         중개거래          강릉시
..     ...  ..     ...           ...      ...    ...   ...          ...
127  32000  13  2018.0       선수촌로 10      NaN         중개거래  강릉시, 서울 서초구
128  43800   3  2016.0       선수촌로 55      NaN         중개거래          강릉시
129  45500   7  2016.0       선수촌로 55      NaN         중개거래          강릉시
130  36000  11  2019.0       회산로 313      NaN         중개거래          강릉시
131  39000  11  2018.0   회산로383번길 37      NaN         중개거래          강릉시

             단가
0    384.615385
1    364.942021
2    378.054403
3    408.401400
4    335.333569
..          ...
127  533.511170
128  515.389313
129  535.408128
130  423.723826
131  458.864017

[132 rows x 17 columns]

In [28]:
dfF = df[df['시군구'].str.contains('강릉')]
# 거래금액 평균은 2억 1천만 원이다.
print(dfF['거래금액'].mean())

21161.257575757576